using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Text;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;

namespace EngineManager
{
    public partial class IconClassForm : Form
    {
        List<DBIconClass> icons_list = new List<DBIconClass>();
        public IconClassForm()
        {
            InitializeComponent();

             //stores the list
            //populate the list here
            XmlDocument doc = new XmlDocument();

            #region IconsXML


            doc.LoadXml(@"
<icons>
<i class='fa-500px' value='f26e' />
<i class='fa-address-book' value='f2b9' />
<i class='fa-address-book-o' value='f2ba' />
<i class='fa-address-card' value='f2bb' />
<i class='fa-address-card-o' value='f2bc' />
<i class='fa-adjust' value='f042' />
<i class='fa-adn' value='f170' />
<i class='fa-align-center' value='f037' />
<i class='fa-align-justify' value='f039' />
<i class='fa-align-left' value='f036' />
<i class='fa-align-right' value='f038' />
<i class='fa-amazon' value='f270' />
<i class='fa-ambulance' value='f0f9' />
<i class='fa-american-sign-language-interpreting' value='f2a3' />
<i class='fa-anchor' value='f13d' />
<i class='fa-android' value='f17b' />
<i class='fa-angellist' value='f209' />
<i class='fa-angle-double-down' value='f103' />
<i class='fa-angle-double-left' value='f100' />
<i class='fa-angle-double-right' value='f101' />
<i class='fa-angle-double-up' value='f102' />
<i class='fa-angle-down' value='f107' />
<i class='fa-angle-left' value='f104' />
<i class='fa-angle-right' value='f105' />
<i class='fa-angle-up' value='f106' />
<i class='fa-apple' value='f179' />
<i class='fa-archive' value='f187' />
<i class='fa-area-chart' value='f1fe' />
<i class='fa-arrow-circle-down' value='f0ab' />
<i class='fa-arrow-circle-left' value='f0a8' />
<i class='fa-arrow-circle-o-down' value='f01a' />
<i class='fa-arrow-circle-o-left' value='f190' />
<i class='fa-arrow-circle-o-right' value='f18e' />
<i class='fa-arrow-circle-o-up' value='f01b' />
<i class='fa-arrow-circle-right' value='f0a9' />
<i class='fa-arrow-circle-up' value='f0aa' />
<i class='fa-arrow-down' value='f063' />
<i class='fa-arrow-left' value='f060' />
<i class='fa-arrow-right' value='f061' />
<i class='fa-arrow-up' value='f062' />
<i class='fa-arrows' value='f047' />
<i class='fa-arrows-alt' value='f0b2' />
<i class='fa-arrows-h' value='f07e' />
<i class='fa-arrows-v' value='f07d' />
<i class='fa-asl-interpreting' value='f2a3' />
<i class='fa-assistive-listening-systems' value='f2a2' />
<i class='fa-asterisk' value='f069' />
<i class='fa-at' value='f1fa' />
<i class='fa-audio-description' value='f29e' />
<i class='fa-automobile' value='f1b9' />
<i class='fa-backward' value='f04a' />
<i class='fa-balance-scale' value='f24e' />
<i class='fa-ban' value='f05e' />
<i class='fa-bandcamp' value='f2d5' />
<i class='fa-bank' value='f19c' />
<i class='fa-bar-chart' value='f080' />
<i class='fa-bar-chart-o' value='f080' />
<i class='fa-barcode' value='f02a' />
<i class='fa-bars' value='f0c9' />
<i class='fa-bath' value='f2cd' />
<i class='fa-bathtub' value='f2cd' />
<i class='fa-battery' value='f240' />
<i class='fa-battery-0' value='f244' />
<i class='fa-battery-1' value='f243' />
<i class='fa-battery-2' value='f242' />
<i class='fa-battery-3' value='f241' />
<i class='fa-battery-4' value='f240' />
<i class='fa-battery-empty' value='f244' />
<i class='fa-battery-full' value='f240' />
<i class='fa-battery-half' value='f242' />
<i class='fa-battery-quarter' value='f243' />
<i class='fa-battery-three-quarters' value='f241' />
<i class='fa-bed' value='f236' />
<i class='fa-beer' value='f0fc' />
<i class='fa-behance' value='f1b4' />
<i class='fa-behance-square' value='f1b5' />
<i class='fa-bell' value='f0f3' />
<i class='fa-bell-o' value='f0a2' />
<i class='fa-bell-slash' value='f1f6' />
<i class='fa-bell-slash-o' value='f1f7' />
<i class='fa-bicycle' value='f206' />
<i class='fa-binoculars' value='f1e5' />
<i class='fa-birthday-cake' value='f1fd' />
<i class='fa-bitbucket' value='f171' />
<i class='fa-bitbucket-square' value='f172' />
<i class='fa-bitcoin' value='f15a' />
<i class='fa-black-tie' value='f27e' />
<i class='fa-blind' value='f29d' />
<i class='fa-bluetooth' value='f293' />
<i class='fa-bluetooth-b' value='f294' />
<i class='fa-bold' value='f032' />
<i class='fa-bolt' value='f0e7' />
<i class='fa-bomb' value='f1e2' />
<i class='fa-book' value='f02d' />
<i class='fa-bookmark' value='f02e' />
<i class='fa-bookmark-o' value='f097' />
<i class='fa-braille' value='f2a1' />
<i class='fa-briefcase' value='f0b1' />
<i class='fa-btc' value='f15a' />
<i class='fa-bug' value='f188' />
<i class='fa-building' value='f1ad' />
<i class='fa-building-o' value='f0f7' />
<i class='fa-bullhorn' value='f0a1' />
<i class='fa-bullseye' value='f140' />
<i class='fa-bus' value='f207' />
<i class='fa-buysellads' value='f20d' />
<i class='fa-cab' value='f1ba' />
<i class='fa-calculator' value='f1ec' />
<i class='fa-calendar' value='f073' />
<i class='fa-calendar-check-o' value='f274' />
<i class='fa-calendar-minus-o' value='f272' />
<i class='fa-calendar-o' value='f133' />
<i class='fa-calendar-plus-o' value='f271' />
<i class='fa-calendar-times-o' value='f273' />
<i class='fa-camera' value='f030' />
<i class='fa-camera-retro' value='f083' />
<i class='fa-car' value='f1b9' />
<i class='fa-caret-down' value='f0d7' />
<i class='fa-caret-left' value='f0d9' />
<i class='fa-caret-right' value='f0da' />
<i class='fa-caret-square-o-down' value='f150' />
<i class='fa-caret-square-o-left' value='f191' />
<i class='fa-caret-square-o-right' value='f152' />
<i class='fa-caret-square-o-up' value='f151' />
<i class='fa-caret-up' value='f0d8' />
<i class='fa-cart-arrow-down' value='f218' />
<i class='fa-cart-plus' value='f217' />
<i class='fa-cc' value='f20a' />
<i class='fa-cc-amex' value='f1f3' />
<i class='fa-cc-diners-club' value='f24c' />
<i class='fa-cc-discover' value='f1f2' />
<i class='fa-cc-jcb' value='f24b' />
<i class='fa-cc-mastercard' value='f1f1' />
<i class='fa-cc-paypal' value='f1f4' />
<i class='fa-cc-stripe' value='f1f5' />
<i class='fa-cc-visa' value='f1f0' />
<i class='fa-certificate' value='f0a3' />
<i class='fa-chain' value='f0c1' />
<i class='fa-chain-broken' value='f127' />
<i class='fa-check' value='f00c' />
<i class='fa-check-circle' value='f058' />
<i class='fa-check-circle-o' value='f05d' />
<i class='fa-check-square' value='f14a' />
<i class='fa-check-square-o' value='f046' />
<i class='fa-chevron-circle-down' value='f13a' />
<i class='fa-chevron-circle-left' value='f137' />
<i class='fa-chevron-circle-right' value='f138' />
<i class='fa-chevron-circle-up' value='f139' />
<i class='fa-chevron-down' value='f078' />
<i class='fa-chevron-left' value='f053' />
<i class='fa-chevron-right' value='f054' />
<i class='fa-chevron-up' value='f077' />
<i class='fa-child' value='f1ae' />
<i class='fa-chrome' value='f268' />
<i class='fa-circle' value='f111' />
<i class='fa-circle-o' value='f10c' />
<i class='fa-circle-o-notch' value='f1ce' />
<i class='fa-circle-thin' value='f1db' />
<i class='fa-clipboard' value='f0ea' />
<i class='fa-clock-o' value='f017' />
<i class='fa-clone' value='f24d' />
<i class='fa-close' value='f00d' />
<i class='fa-cloud' value='f0c2' />
<i class='fa-cloud-download' value='f0ed' />
<i class='fa-cloud-upload' value='f0ee' />
<i class='fa-cny' value='f157' />
<i class='fa-code' value='f121' />
<i class='fa-code-fork' value='f126' />
<i class='fa-codepen' value='f1cb' />
<i class='fa-codiepie' value='f284' />
<i class='fa-coffee' value='f0f4' />
<i class='fa-cog' value='f013' />
<i class='fa-cogs' value='f085' />
<i class='fa-columns' value='f0db' />
<i class='fa-comment' value='f075' />
<i class='fa-comment-o' value='f0e5' />
<i class='fa-commenting' value='f27a' />
<i class='fa-commenting-o' value='f27b' />
<i class='fa-comments' value='f086' />
<i class='fa-comments-o' value='f0e6' />
<i class='fa-compass' value='f14e' />
<i class='fa-compress' value='f066' />
<i class='fa-connectdevelop' value='f20e' />
<i class='fa-contao' value='f26d' />
<i class='fa-copy' value='f0c5' />
<i class='fa-copyright' value='f1f9' />
<i class='fa-creative-commons' value='f25e' />
<i class='fa-credit-card' value='f09d' />
<i class='fa-credit-card-alt' value='f283' />
<i class='fa-crop' value='f125' />
<i class='fa-crosshairs' value='f05b' />
<i class='fa-css3' value='f13c' />
<i class='fa-cube' value='f1b2' />
<i class='fa-cubes' value='f1b3' />
<i class='fa-cut' value='f0c4' />
<i class='fa-cutlery' value='f0f5' />
<i class='fa-dashboard' value='f0e4' />
<i class='fa-dashcube' value='f210' />
<i class='fa-database' value='f1c0' />
<i class='fa-deaf' value='f2a4' />
<i class='fa-deafness' value='f2a4' />
<i class='fa-dedent' value='f03b' />
<i class='fa-delicious' value='f1a5' />
<i class='fa-desktop' value='f108' />
<i class='fa-deviantart' value='f1bd' />
<i class='fa-diamond' value='f219' />
<i class='fa-digg' value='f1a6' />
<i class='fa-dollar' value='f155' />
<i class='fa-dot-circle-o' value='f192' />
<i class='fa-download' value='f019' />
<i class='fa-dribbble' value='f17d' />
<i class='fa-drivers-license' value='f2c2' />
<i class='fa-drivers-license-o' value='f2c3' />
<i class='fa-dropbox' value='f16b' />
<i class='fa-drupal' value='f1a9' />
<i class='fa-edge' value='f282' />
<i class='fa-edit' value='f044' />
<i class='fa-eercast' value='f2da' />
<i class='fa-eject' value='f052' />
<i class='fa-ellipsis-h' value='f141' />
<i class='fa-ellipsis-v' value='f142' />
<i class='fa-empire' value='f1d1' />
<i class='fa-envelope' value='f0e0' />
<i class='fa-envelope-o' value='f003' />
<i class='fa-envelope-open' value='f2b6' />
<i class='fa-envelope-open-o' value='f2b7' />
<i class='fa-envelope-square' value='f199' />
<i class='fa-envira' value='f299' />
<i class='fa-eraser' value='f12d' />
<i class='fa-etsy' value='f2d7' />
<i class='fa-eur' value='f153' />
<i class='fa-euro' value='f153' />
<i class='fa-exchange' value='f0ec' />
<i class='fa-exclamation' value='f12a' />
<i class='fa-exclamation-circle' value='f06a' />
<i class='fa-exclamation-triangle' value='f071' />
<i class='fa-expand' value='f065' />
<i class='fa-expeditedssl' value='f23e' />
<i class='fa-external-link' value='f08e' />
<i class='fa-external-link-square' value='f14c' />
<i class='fa-eye' value='f06e' />
<i class='fa-eye-slash' value='f070' />
<i class='fa-eyedropper' value='f1fb' />
<i class='fa-fa' value='f2b4' />
<i class='fa-facebook' value='f09a' />
<i class='fa-facebook-f' value='f09a' />
<i class='fa-facebook-official' value='f230' />
<i class='fa-facebook-square' value='f082' />
<i class='fa-fast-backward' value='f049' />
<i class='fa-fast-forward' value='f050' />
<i class='fa-fax' value='f1ac' />
<i class='fa-feed' value='f09e' />
<i class='fa-female' value='f182' />
<i class='fa-fighter-jet' value='f0fb' />
<i class='fa-file' value='f15b' />
<i class='fa-file-archive-o' value='f1c6' />
<i class='fa-file-audio-o' value='f1c7' />
<i class='fa-file-code-o' value='f1c9' />
<i class='fa-file-excel-o' value='f1c3' />
<i class='fa-file-image-o' value='f1c5' />
<i class='fa-file-movie-o' value='f1c8' />
<i class='fa-file-o' value='f016' />
<i class='fa-file-pdf-o' value='f1c1' />
<i class='fa-file-photo-o' value='f1c5' />
<i class='fa-file-picture-o' value='f1c5' />
<i class='fa-file-powerpoint-o' value='f1c4' />
<i class='fa-file-sound-o' value='f1c7' />
<i class='fa-file-text' value='f15c' />
<i class='fa-file-text-o' value='f0f6' />
<i class='fa-file-video-o' value='f1c8' />
<i class='fa-file-word-o' value='f1c2' />
<i class='fa-file-zip-o' value='f1c6' />
<i class='fa-files-o' value='f0c5' />
<i class='fa-film' value='f008' />
<i class='fa-filter' value='f0b0' />
<i class='fa-fire' value='f06d' />
<i class='fa-fire-extinguisher' value='f134' />
<i class='fa-firefox' value='f269' />
<i class='fa-first-order' value='f2b0' />
<i class='fa-flag' value='f024' />
<i class='fa-flag-checkered' value='f11e' />
<i class='fa-flag-o' value='f11d' />
<i class='fa-flash' value='f0e7' />
<i class='fa-flask' value='f0c3' />
<i class='fa-flickr' value='f16e' />
<i class='fa-floppy-o' value='f0c7' />
<i class='fa-folder' value='f07b' />
<i class='fa-folder-o' value='f114' />
<i class='fa-folder-open' value='f07c' />
<i class='fa-folder-open-o' value='f115' />
<i class='fa-font' value='f031' />
<i class='fa-font-awesome' value='f2b4' />
<i class='fa-fonticons' value='f280' />
<i class='fa-fort-awesome' value='f286' />
<i class='fa-forumbee' value='f211' />
<i class='fa-forward' value='f04e' />
<i class='fa-foursquare' value='f180' />
<i class='fa-free-code-camp' value='f2c5' />
<i class='fa-frown-o' value='f119' />
<i class='fa-futbol-o' value='f1e3' />
<i class='fa-gamepad' value='f11b' />
<i class='fa-gavel' value='f0e3' />
<i class='fa-gbp' value='f154' />
<i class='fa-ge' value='f1d1' />
<i class='fa-gear' value='f013' />
<i class='fa-gears' value='f085' />
<i class='fa-genderless' value='f22d' />
<i class='fa-get-pocket' value='f265' />
<i class='fa-gg' value='f260' />
<i class='fa-gg-circle' value='f261' />
<i class='fa-gift' value='f06b' />
<i class='fa-git' value='f1d3' />
<i class='fa-git-square' value='f1d2' />
<i class='fa-github' value='f09b' />
<i class='fa-github-alt' value='f113' />
<i class='fa-github-square' value='f092' />
<i class='fa-gitlab' value='f296' />
<i class='fa-gittip' value='f184' />
<i class='fa-glass' value='f000' />
<i class='fa-glide' value='f2a5' />
<i class='fa-glide-g' value='f2a6' />
<i class='fa-globe' value='f0ac' />
<i class='fa-google' value='f1a0' />
<i class='fa-google-plus' value='f0d5' />
<i class='fa-google-plus-circle' value='f2b3' />
<i class='fa-google-plus-official' value='f2b3' />
<i class='fa-google-plus-square' value='f0d4' />
<i class='fa-google-wallet' value='f1ee' />
<i class='fa-graduation-cap' value='f19d' />
<i class='fa-gratipay' value='f184' />
<i class='fa-grav' value='f2d6' />
<i class='fa-group' value='f0c0' />
<i class='fa-h-square' value='f0fd' />
<i class='fa-hacker-news' value='f1d4' />
<i class='fa-hand-grab-o' value='f255' />
<i class='fa-hand-lizard-o' value='f258' />
<i class='fa-hand-o-down' value='f0a7' />
<i class='fa-hand-o-left' value='f0a5' />
<i class='fa-hand-o-right' value='f0a4' />
<i class='fa-hand-o-up' value='f0a6' />
<i class='fa-hand-paper-o' value='f256' />
<i class='fa-hand-peace-o' value='f25b' />
<i class='fa-hand-pointer-o' value='f25a' />
<i class='fa-hand-rock-o' value='f255' />
<i class='fa-hand-scissors-o' value='f257' />
<i class='fa-hand-spock-o' value='f259' />
<i class='fa-hand-stop-o' value='f256' />
<i class='fa-handshake-o' value='f2b5' />
<i class='fa-hard-of-hearing' value='f2a4' />
<i class='fa-hashtag' value='f292' />
<i class='fa-hdd-o' value='f0a0' />
<i class='fa-header' value='f1dc' />
<i class='fa-headphones' value='f025' />
<i class='fa-heart' value='f004' />
<i class='fa-heart-o' value='f08a' />
<i class='fa-heartbeat' value='f21e' />
<i class='fa-history' value='f1da' />
<i class='fa-home' value='f015' />
<i class='fa-hospital-o' value='f0f8' />
<i class='fa-hotel' value='f236' />
<i class='fa-hourglass' value='f254' />
<i class='fa-hourglass-1' value='f251' />
<i class='fa-hourglass-2' value='f252' />
<i class='fa-hourglass-3' value='f253' />
<i class='fa-hourglass-end' value='f253' />
<i class='fa-hourglass-half' value='f252' />
<i class='fa-hourglass-o' value='f250' />
<i class='fa-hourglass-start' value='f251' />
<i class='fa-houzz' value='f27c' />
<i class='fa-html5' value='f13b' />
<i class='fa-i-cursor' value='f246' />
<i class='fa-id-badge' value='f2c1' />
<i class='fa-id-card' value='f2c2' />
<i class='fa-id-card-o' value='f2c3' />
<i class='fa-ils' value='f20b' />
<i class='fa-image' value='f03e' />
<i class='fa-imdb' value='f2d8' />
<i class='fa-inbox' value='f01c' />
<i class='fa-indent' value='f03c' />
<i class='fa-industry' value='f275' />
<i class='fa-info' value='f129' />
<i class='fa-info-circle' value='f05a' />
<i class='fa-inr' value='f156' />
<i class='fa-instagram' value='f16d' />
<i class='fa-institution' value='f19c' />
<i class='fa-internet-explorer' value='f26b' />
<i class='fa-intersex' value='f224' />
<i class='fa-ioxhost' value='f208' />
<i class='fa-italic' value='f033' />
<i class='fa-joomla' value='f1aa' />
<i class='fa-jpy' value='f157' />
<i class='fa-jsfiddle' value='f1cc' />
<i class='fa-key' value='f084' />
<i class='fa-keyboard-o' value='f11c' />
<i class='fa-krw' value='f159' />
<i class='fa-language' value='f1ab' />
<i class='fa-laptop' value='f109' />
<i class='fa-lastfm' value='f202' />
<i class='fa-lastfm-square' value='f203' />
<i class='fa-leaf' value='f06c' />
<i class='fa-leanpub' value='f212' />
<i class='fa-legal' value='f0e3' />
<i class='fa-lemon-o' value='f094' />
<i class='fa-level-down' value='f149' />
<i class='fa-level-up' value='f148' />
<i class='fa-life-bouy' value='f1cd' />
<i class='fa-life-buoy' value='f1cd' />
<i class='fa-life-ring' value='f1cd' />
<i class='fa-life-saver' value='f1cd' />
<i class='fa-lightbulb-o' value='f0eb' />
<i class='fa-line-chart' value='f201' />
<i class='fa-link' value='f0c1' />
<i class='fa-linkedin' value='f0e1' />
<i class='fa-linkedin-square' value='f08c' />
<i class='fa-linode' value='f2b8' />
<i class='fa-linux' value='f17c' />
<i class='fa-list' value='f03a' />
<i class='fa-list-alt' value='f022' />
<i class='fa-list-ol' value='f0cb' />
<i class='fa-list-ul' value='f0ca' />
<i class='fa-location-arrow' value='f124' />
<i class='fa-lock' value='f023' />
<i class='fa-long-arrow-down' value='f175' />
<i class='fa-long-arrow-left' value='f177' />
<i class='fa-long-arrow-right' value='f178' />
<i class='fa-long-arrow-up' value='f176' />
<i class='fa-low-vision' value='f2a8' />
<i class='fa-magic' value='f0d0' />
<i class='fa-magnet' value='f076' />
<i class='fa-mail-forward' value='f064' />
<i class='fa-mail-reply' value='f112' />
<i class='fa-mail-reply-all' value='f122' />
<i class='fa-male' value='f183' />
<i class='fa-map' value='f279' />
<i class='fa-map-marker' value='f041' />
<i class='fa-map-o' value='f278' />
<i class='fa-map-pin' value='f276' />
<i class='fa-map-signs' value='f277' />
<i class='fa-mars' value='f222' />
<i class='fa-mars-double' value='f227' />
<i class='fa-mars-stroke' value='f229' />
<i class='fa-mars-stroke-h' value='f22b' />
<i class='fa-mars-stroke-v' value='f22a' />
<i class='fa-maxcdn' value='f136' />
<i class='fa-meanpath' value='f20c' />
<i class='fa-medium' value='f23a' />
<i class='fa-medkit' value='f0fa' />
<i class='fa-meetup' value='f2e0' />
<i class='fa-meh-o' value='f11a' />
<i class='fa-mercury' value='f223' />
<i class='fa-microchip' value='f2db' />
<i class='fa-microphone' value='f130' />
<i class='fa-microphone-slash' value='f131' />
<i class='fa-minus' value='f068' />
<i class='fa-minus-circle' value='f056' />
<i class='fa-minus-square' value='f146' />
<i class='fa-minus-square-o' value='f147' />
<i class='fa-mixcloud' value='f289' />
<i class='fa-mobile' value='f10b' />
<i class='fa-mobile-phone' value='f10b' />
<i class='fa-modx' value='f285' />
<i class='fa-money' value='f0d6' />
<i class='fa-moon-o' value='f186' />
<i class='fa-mortar-board' value='f19d' />
<i class='fa-motorcycle' value='f21c' />
<i class='fa-mouse-pointer' value='f245' />
<i class='fa-music' value='f001' />
<i class='fa-navicon' value='f0c9' />
<i class='fa-neuter' value='f22c' />
<i class='fa-newspaper-o' value='f1ea' />
<i class='fa-object-group' value='f247' />
<i class='fa-object-ungroup' value='f248' />
<i class='fa-odnoklassniki' value='f263' />
<i class='fa-odnoklassniki-square' value='f264' />
<i class='fa-opencart' value='f23d' />
<i class='fa-openid' value='f19b' />
<i class='fa-opera' value='f26a' />
<i class='fa-optin-monster' value='f23c' />
<i class='fa-outdent' value='f03b' />
<i class='fa-pagelines' value='f18c' />
<i class='fa-paint-brush' value='f1fc' />
<i class='fa-paper-plane' value='f1d8' />
<i class='fa-paper-plane-o' value='f1d9' />
<i class='fa-paperclip' value='f0c6' />
<i class='fa-paragraph' value='f1dd' />
<i class='fa-paste' value='f0ea' />
<i class='fa-pause' value='f04c' />
<i class='fa-pause-circle' value='f28b' />
<i class='fa-pause-circle-o' value='f28c' />
<i class='fa-paw' value='f1b0' />
<i class='fa-paypal' value='f1ed' />
<i class='fa-pencil' value='f040' />
<i class='fa-pencil-square' value='f14b' />
<i class='fa-pencil-square-o' value='f044' />
<i class='fa-percent' value='f295' />
<i class='fa-phone' value='f095' />
<i class='fa-phone-square' value='f098' />
<i class='fa-photo' value='f03e' />
<i class='fa-picture-o' value='f03e' />
<i class='fa-pie-chart' value='f200' />
<i class='fa-pied-piper' value='f2ae' />
<i class='fa-pied-piper-alt' value='f1a8' />
<i class='fa-pied-piper-pp' value='f1a7' />
<i class='fa-pinterest' value='f0d2' />
<i class='fa-pinterest-p' value='f231' />
<i class='fa-pinterest-square' value='f0d3' />
<i class='fa-plane' value='f072' />
<i class='fa-play' value='f04b' />
<i class='fa-play-circle' value='f144' />
<i class='fa-play-circle-o' value='f01d' />
<i class='fa-plug' value='f1e6' />
<i class='fa-plus' value='f067' />
<i class='fa-plus-circle' value='f055' />
<i class='fa-plus-square' value='f0fe' />
<i class='fa-plus-square-o' value='f196' />
<i class='fa-podcast' value='f2ce' />
<i class='fa-power-off' value='f011' />
<i class='fa-print' value='f02f' />
<i class='fa-product-hunt' value='f288' />
<i class='fa-puzzle-piece' value='f12e' />
<i class='fa-qq' value='f1d6' />
<i class='fa-qrcode' value='f029' />
<i class='fa-question' value='f128' />
<i class='fa-question-circle' value='f059' />
<i class='fa-question-circle-o' value='f29c' />
<i class='fa-quora' value='f2c4' />
<i class='fa-quote-left' value='f10d' />
<i class='fa-quote-right' value='f10e' />
<i class='fa-ra' value='f1d0' />
<i class='fa-random' value='f074' />
<i class='fa-ravelry' value='f2d9' />
<i class='fa-rebel' value='f1d0' />
<i class='fa-recycle' value='f1b8' />
<i class='fa-reddit' value='f1a1' />
<i class='fa-reddit-alien' value='f281' />
<i class='fa-reddit-square' value='f1a2' />
<i class='fa-refresh' value='f021' />
<i class='fa-registered' value='f25d' />
<i class='fa-remove' value='f00d' />
<i class='fa-renren' value='f18b' />
<i class='fa-reorder' value='f0c9' />
<i class='fa-repeat' value='f01e' />
<i class='fa-reply' value='f112' />
<i class='fa-reply-all' value='f122' />
<i class='fa-resistance' value='f1d0' />
<i class='fa-retweet' value='f079' />
<i class='fa-rmb' value='f157' />
<i class='fa-road' value='f018' />
<i class='fa-rocket' value='f135' />
<i class='fa-rotate-left' value='f0e2' />
<i class='fa-rotate-right' value='f01e' />
<i class='fa-rouble' value='f158' />
<i class='fa-rss' value='f09e' />
<i class='fa-rss-square' value='f143' />
<i class='fa-rub' value='f158' />
<i class='fa-ruble' value='f158' />
<i class='fa-rupee' value='f156' />
<i class='fa-s15' value='f2cd' />
<i class='fa-safari' value='f267' />
<i class='fa-save' value='f0c7' />
<i class='fa-scissors' value='f0c4' />
<i class='fa-scribd' value='f28a' />
<i class='fa-search' value='f002' />
<i class='fa-search-minus' value='f010' />
<i class='fa-search-plus' value='f00e' />
<i class='fa-sellsy' value='f213' />
<i class='fa-send' value='f1d8' />
<i class='fa-send-o' value='f1d9' />
<i class='fa-server' value='f233' />
<i class='fa-share' value='f064' />
<i class='fa-share-alt' value='f1e0' />
<i class='fa-share-alt-square' value='f1e1' />
<i class='fa-share-square' value='f14d' />
<i class='fa-share-square-o' value='f045' />
<i class='fa-shekel' value='f20b' />
<i class='fa-sheqel' value='f20b' />
<i class='fa-shield' value='f132' />
<i class='fa-ship' value='f21a' />
<i class='fa-shirtsinbulk' value='f214' />
<i class='fa-shopping-bag' value='f290' />
<i class='fa-shopping-basket' value='f291' />
<i class='fa-shopping-cart' value='f07a' />
<i class='fa-shower' value='f2cc' />
<i class='fa-sign-in' value='f090' />
<i class='fa-sign-language' value='f2a7' />
<i class='fa-sign-out' value='f08b' />
<i class='fa-signal' value='f012' />
<i class='fa-signing' value='f2a7' />
<i class='fa-simplybuilt' value='f215' />
<i class='fa-sitemap' value='f0e8' />
<i class='fa-skyatlas' value='f216' />
<i class='fa-skype' value='f17e' />
<i class='fa-slack' value='f198' />
<i class='fa-sliders' value='f1de' />
<i class='fa-slideshare' value='f1e7' />
<i class='fa-smile-o' value='f118' />
<i class='fa-snapchat' value='f2ab' />
<i class='fa-snapchat-ghost' value='f2ac' />
<i class='fa-snapchat-square' value='f2ad' />
<i class='fa-snowflake-o' value='f2dc' />
<i class='fa-soccer-ball-o' value='f1e3' />
<i class='fa-sort' value='f0dc' />
<i class='fa-sort-alpha-asc' value='f15d' />
<i class='fa-sort-alpha-desc' value='f15e' />
<i class='fa-sort-amount-asc' value='f160' />
<i class='fa-sort-amount-desc' value='f161' />
<i class='fa-sort-asc' value='f0de' />
<i class='fa-sort-desc' value='f0dd' />
<i class='fa-sort-down' value='f0dd' />
<i class='fa-sort-numeric-asc' value='f162' />
<i class='fa-sort-numeric-desc' value='f163' />
<i class='fa-sort-up' value='f0de' />
<i class='fa-soundcloud' value='f1be' />
<i class='fa-space-shuttle' value='f197' />
<i class='fa-spinner' value='f110' />
<i class='fa-spoon' value='f1b1' />
<i class='fa-spotify' value='f1bc' />
<i class='fa-square' value='f0c8' />
<i class='fa-square-o' value='f096' />
<i class='fa-stack-exchange' value='f18d' />
<i class='fa-stack-overflow' value='f16c' />
<i class='fa-star' value='f005' />
<i class='fa-star-half' value='f089' />
<i class='fa-star-half-empty' value='f123' />
<i class='fa-star-half-full' value='f123' />
<i class='fa-star-half-o' value='f123' />
<i class='fa-star-o' value='f006' />
<i class='fa-steam' value='f1b6' />
<i class='fa-steam-square' value='f1b7' />
<i class='fa-step-backward' value='f048' />
<i class='fa-step-forward' value='f051' />
<i class='fa-stethoscope' value='f0f1' />
<i class='fa-sticky-note' value='f249' />
<i class='fa-sticky-note-o' value='f24a' />
<i class='fa-stop' value='f04d' />
<i class='fa-stop-circle' value='f28d' />
<i class='fa-stop-circle-o' value='f28e' />
<i class='fa-street-view' value='f21d' />
<i class='fa-strikethrough' value='f0cc' />
<i class='fa-stumbleupon' value='f1a4' />
<i class='fa-stumbleupon-circle' value='f1a3' />
<i class='fa-subscript' value='f12c' />
<i class='fa-subway' value='f239' />
<i class='fa-suitcase' value='f0f2' />
<i class='fa-sun-o' value='f185' />
<i class='fa-superpowers' value='f2dd' />
<i class='fa-superscript' value='f12b' />
<i class='fa-support' value='f1cd' />
<i class='fa-table' value='f0ce' />
<i class='fa-tablet' value='f10a' />
<i class='fa-tachometer' value='f0e4' />
<i class='fa-tag' value='f02b' />
<i class='fa-tags' value='f02c' />
<i class='fa-tasks' value='f0ae' />
<i class='fa-taxi' value='f1ba' />
<i class='fa-telegram' value='f2c6' />
<i class='fa-television' value='f26c' />
<i class='fa-tencent-weibo' value='f1d5' />
<i class='fa-terminal' value='f120' />
<i class='fa-text-height' value='f034' />
<i class='fa-text-width' value='f035' />
<i class='fa-th' value='f00a' />
<i class='fa-th-large' value='f009' />
<i class='fa-th-list' value='f00b' />
<i class='fa-themeisle' value='f2b2' />
<i class='fa-thermometer' value='f2c7' />
<i class='fa-thermometer-0' value='f2cb' />
<i class='fa-thermometer-1' value='f2ca' />
<i class='fa-thermometer-2' value='f2c9' />
<i class='fa-thermometer-3' value='f2c8' />
<i class='fa-thermometer-4' value='f2c7' />
<i class='fa-thermometer-empty' value='f2cb' />
<i class='fa-thermometer-full' value='f2c7' />
<i class='fa-thermometer-half' value='f2c9' />
<i class='fa-thermometer-quarter' value='f2ca' />
<i class='fa-thermometer-three-quarters' value='f2c8' />
<i class='fa-thumb-tack' value='f08d' />
<i class='fa-thumbs-down' value='f165' />
<i class='fa-thumbs-o-down' value='f088' />
<i class='fa-thumbs-o-up' value='f087' />
<i class='fa-thumbs-up' value='f164' />
<i class='fa-ticket' value='f145' />
<i class='fa-times' value='f00d' />
<i class='fa-times-circle' value='f057' />
<i class='fa-times-circle-o' value='f05c' />
<i class='fa-times-rectangle' value='f2d3' />
<i class='fa-times-rectangle-o' value='f2d4' />
<i class='fa-tint' value='f043' />
<i class='fa-toggle-down' value='f150' />
<i class='fa-toggle-left' value='f191' />
<i class='fa-toggle-off' value='f204' />
<i class='fa-toggle-on' value='f205' />
<i class='fa-toggle-right' value='f152' />
<i class='fa-toggle-up' value='f151' />
<i class='fa-trademark' value='f25c' />
<i class='fa-train' value='f238' />
<i class='fa-transgender' value='f224' />
<i class='fa-transgender-alt' value='f225' />
<i class='fa-trash' value='f1f8' />
<i class='fa-trash-o' value='f014' />
<i class='fa-tree' value='f1bb' />
<i class='fa-trello' value='f181' />
<i class='fa-tripadvisor' value='f262' />
<i class='fa-trophy' value='f091' />
<i class='fa-truck' value='f0d1' />
<i class='fa-try' value='f195' />
<i class='fa-tty' value='f1e4' />
<i class='fa-tumblr' value='f173' />
<i class='fa-tumblr-square' value='f174' />
<i class='fa-turkish-lira' value='f195' />
<i class='fa-tv' value='f26c' />
<i class='fa-twitch' value='f1e8' />
<i class='fa-twitter' value='f099' />
<i class='fa-twitter-square' value='f081' />
<i class='fa-umbrella' value='f0e9' />
<i class='fa-underline' value='f0cd' />
<i class='fa-undo' value='f0e2' />
<i class='fa-universal-access' value='f29a' />
<i class='fa-university' value='f19c' />
<i class='fa-unlink' value='f127' />
<i class='fa-unlock' value='f09c' />
<i class='fa-unlock-alt' value='f13e' />
<i class='fa-unsorted' value='f0dc' />
<i class='fa-upload' value='f093' />
<i class='fa-usb' value='f287' />
<i class='fa-usd' value='f155' />
<i class='fa-user' value='f007' />
<i class='fa-user-circle' value='f2bd' />
<i class='fa-user-circle-o' value='f2be' />
<i class='fa-user-md' value='f0f0' />
<i class='fa-user-o' value='f2c0' />
<i class='fa-user-plus' value='f234' />
<i class='fa-user-secret' value='f21b' />
<i class='fa-user-times' value='f235' />
<i class='fa-users' value='f0c0' />
<i class='fa-vcard' value='f2bb' />
<i class='fa-vcard-o' value='f2bc' />
<i class='fa-venus' value='f221' />
<i class='fa-venus-double' value='f226' />
<i class='fa-venus-mars' value='f228' />
<i class='fa-viacoin' value='f237' />
<i class='fa-viadeo' value='f2a9' />
<i class='fa-viadeo-square' value='f2aa' />
<i class='fa-video-camera' value='f03d' />
<i class='fa-vimeo' value='f27d' />
<i class='fa-vimeo-square' value='f194' />
<i class='fa-vine' value='f1ca' />
<i class='fa-vk' value='f189' />
<i class='fa-volume-control-phone' value='f2a0' />
<i class='fa-volume-down' value='f027' />
<i class='fa-volume-off' value='f026' />
<i class='fa-volume-up' value='f028' />
<i class='fa-warning' value='f071' />
<i class='fa-wechat' value='f1d7' />
<i class='fa-weibo' value='f18a' />
<i class='fa-weixin' value='f1d7' />
<i class='fa-whatsapp' value='f232' />
<i class='fa-wheelchair' value='f193' />
<i class='fa-wheelchair-alt' value='f29b' />
<i class='fa-wifi' value='f1eb' />
<i class='fa-wikipedia-w' value='f266' />
<i class='fa-window-close' value='f2d3' />
<i class='fa-window-close-o' value='f2d4' />
<i class='fa-window-maximize' value='f2d0' />
<i class='fa-window-minimize' value='f2d1' />
<i class='fa-window-restore' value='f2d2' />
<i class='fa-windows' value='f17a' />
<i class='fa-won' value='f159' />
<i class='fa-wordpress' value='f19a' />
<i class='fa-wpbeginner' value='f297' />
<i class='fa-wpexplorer' value='f2de' />
<i class='fa-wpforms' value='f298' />
<i class='fa-wrench' value='f0ad' />
<i class='fa-xing' value='f168' />
<i class='fa-xing-square' value='f169' />
<i class='fa-y-combinator' value='f23b' />
<i class='fa-y-combinator-square' value='f1d4' />
<i class='fa-yahoo' value='f19e' />
<i class='fa-yc' value='f23b' />
<i class='fa-yc-square' value='f1d4' />
<i class='fa-yelp' value='f1e9' />
<i class='fa-yen' value='f157' />
<i class='fa-yoast' value='f2b1' />
<i class='fa-youtube' value='f167' />
<i class='fa-youtube-play' value='f16a' />
<i class='fa-youtube-square' value='f166' />
</icons>
");
            #endregion

            foreach (XmlNode n in doc.SelectNodes("//i"))
            {
                icons_list.Add(new DBIconClass { Class = "fa " + n.Attributes["class"].Value, Value = HexToChar(n.Attributes["value"].Value) + " " + n.Attributes["class"].Value });
            }

            listBox1.DataSource = icons_list;
            listBox1.DisplayMember = "Value";
            listBox1.ValueMember = "Class";

            PrivateFontCollection collection = new PrivateFontCollection();
            collection.AddFontFile(Application.StartupPath + @"\font\fontawesome-webfont.ttf");
            FontFamily fontFamily = new FontFamily("FontAwesome", collection);
            Font font = new Font(fontFamily, 20);
            listBox1.Font = font;
        }
        public static string HexToChar(string hex)
        {
            return ((char)ushort.Parse(hex, System.Globalization.NumberStyles.HexNumber)).ToString();
        }
        public DBIconClass Value
        {
            get { return listBox1.SelectedItem as DBIconClass; }
            set { listBox1.SelectedItem = value; }
        }

        private void textBox1_KeyUp(object sender, KeyEventArgs e)
        {

        }

        private void textBox1_TextChanged(object sender, EventArgs e)
        {
            var filtered_list = icons_list.Where(x => x.Class.ToLower().Contains(textBox1.Text.ToLower())).ToList();
            listBox1.DataSource = filtered_list;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            Value.Color = cmb_color.SelectedItem != null ? cmb_color.SelectedItem.ToString() : "";
            Value.Rotate = cmb_rotate.SelectedItem != null ? cmb_rotate.SelectedItem.ToString() : "";
            Value.FixedWidth = cb_width.Checked;
        }

        private void btn_no_icon_Click(object sender, EventArgs e)
        {
            Value = new DBIconClass { Class = "", Value = "", Color = "", FixedWidth = false, Rotate = "" };
        }
    }
}
